---
title: "Taxi EDA"
author: "Zachary Jennings"
date: "2026-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(arrow)
library(dplyr)
library(purrr)
library(tidyverse)
library(lubridate)
library(caret)
```

```{r import-data}
path <- "C:/Users/proza/Documents/SMU/DS6306/Final/Final"

# List all parquet files
files <- list.files(path, pattern = "\\.parquet$", full.names = TRUE)

# Read and row-bind
taxi <- files %>%
  lapply(read_parquet) %>%
  bind_rows()

# Join taxi pickup/drop off location IDs to taxi zone lookup information
locations <- read.csv("taxi_zone_lookup.csv", header = TRUE)

taxi <- taxi %>%
  left_join(locations, by = c("PULocationID" = "LocationID")) %>%
  left_join(locations, by = c("DOLocationID" = "LocationID"), 
            suffix = c("_pickup", "_dropoff"))

head(taxi)
```


```{r mutations}
# Labeling factor variables VendorID, RatecodeID, payment_type. Creating new variables for date/time analysis and tips as a percent of fare
taxi <- taxi %>%
  mutate(#creating Date/Time variables
    month= month(tpep_pickup_datetime,label=TRUE, abbr=FALSE),
    weekday = wday(tpep_pickup_datetime,label=TRUE,abbr=FALSE),
    duration = as.numeric(difftime(tpep_dropoff_datetime, tpep_pickup_datetime,units="mins")), # duration in minutes
    pickup_hour = hour(tpep_pickup_datetime),
    pickup_time_of_day = factor(case_when(
      pickup_hour >= 5  & pickup_hour < 12 ~ "Morning",
      pickup_hour >= 12 & pickup_hour < 17 ~ "Afternoon",
      pickup_hour >= 17 & pickup_hour < 21 ~ "Evening",
      TRUE ~ "Night"
    ), levels = c("Morning","Afternoon","Evening","Night")),
    # Vendor labels
    Vendor_name = case_when(
      VendorID == 1 ~ "Creative Mobile Technologies",
      VendorID == 2 ~ "Curb Mobility",
      VendorID == 6 ~ "Myle Technologies",
      VendorID == 7 ~ "Helix",
      TRUE ~ "Unknown"
    ),
    # Rate code labels
    Ratecode_name = case_when(
      RatecodeID == 1 ~ "Standard",
      RatecodeID == 2 ~ "JFK",
      RatecodeID == 3 ~ "Newark",
      RatecodeID == 4 ~ "Nassau/Westchester",
      RatecodeID == 5 ~ "Negotiated",
      RatecodeID == 6 ~ "Group ride",
      RatecodeID == 99 ~ "Unknown",
      TRUE ~ "Unknown"
    ),
    # Payment type labels
    payment_type_name = case_when(
      payment_type == 0 ~ "Flex fare",
      payment_type == 1 ~ "Credit card",
      payment_type == 2 ~ "Cash",
      payment_type == 3 ~ "No charge",
      payment_type == 4 ~ "Dispute",
      payment_type == 5 ~ "Unknown",
      payment_type == 6 ~ "Voided trip",
      TRUE ~ "Unknown"
    ),
    tip_pct = tip_amount/fare_amount
  )
```

```{r extreme-tip-values}
# Exploring extreme values to see if they're necessary
summary(taxi)
# Percentage of tips > 100% of fare = 0.15%
extreme_tip_pct <- dim(taxi[taxi$tip_amount/taxi$fare_amount>1,])[1]/dim(taxi)[1]*100
extreme_tip_pct

# percentage of tips = $0 when paying with flex fare or credit card = 26.87%
no_tip_pct <- dim(taxi[taxi$tip_amount == 0 & taxi$payment_type %in% c(0,1),])[1]/dim(taxi)[1]*100
no_tip_pct
```

```{r filtering}
# Creating filters to limit our dataset to relevant values
taxi <- taxi %>%
  filter(tip_amount > 0,           # only where tips occured
         tip_pct < 1,              # only reasonable tips < 100% of fare
         trip_distance > 0,        # only trips with distances
         payment_type %in% c(0,1), # only payment types flex fare and credit card
         duration > 0,             # only where drive time is positive
         fare_amount > 0,          # only relevent charged trips
         trip_distance < 100)      # trips over 100 miles must be an input error
dim(taxi)                          # filters limit to 28.8M records instead of > 40M
```

```{r sampling}
# Sampled data to run aggregate analysis and employ CLT
set.seed(123)
taxi_sample <- taxi %>% group_by(Borough_pickup) %>%
  slice_sample(n=500) %>% ungroup()
```


```{r create-sampling-distributions}
# sampling distribution of tips and fare amounts where the tip % is less than 100% of the fare amount
mean_tip_holder       <- c()
mean_fare_holder      <- c()
mean_tip_pct_holder   <- c()

for(i in 1:1000){
  id <- sample(1:nrow(taxi), 100)

  tmp <- taxi[id, ] %>% 
    filter(tip_amount/fare_amount < 1,
           trip_distance >0,
           fare_amount >0) %>%
    summarize(
      mean_tip     = mean(tip_amount),
      mean_fare    = mean(fare_amount),
      mean_tip_pct = mean(tip_amount / fare_amount)
    )

  mean_tip_holder[i]     <- tmp$mean_tip
  mean_fare_holder[i]    <- tmp$mean_fare
  mean_tip_pct_holder[i] <- tmp$mean_tip_pct
}
```
<div data-plot-id="mean_tip_distribution"
     data-tags="tips,sampling, distribution,taxi">
```{r}
# Average tips are usually between 2 - 4 dollars
ggplot(data.frame(mean_tip_holder),aes(mean_tip_holder))+geom_histogram()+
  labs(title="Sampling Distribution of Average Tip Amounts",
       x="Tip Amounts", y="Count")
```
</div>
<div data-plot-id="mean_fare_distribution"
     data-tags="fare,sampling, distribution,taxi">
```{r}
# On average, most fares are between roughly 17 and 23 dollars
ggplot(data.frame(mean_fare_holder),aes(mean_fare_holder))+geom_histogram()+
  labs(title="Sampling Distribution of Average Fare Amounts",
       x="Fare Amounts", y="Count")
```
</div>

<div data-plot-id="mean_tip_pct_distribution"
     data-tags="tips,tips,percent,sampling, distribution,taxi">
```{r}
# On average, most tip percents are between roughly 14 and 19 percent of the fare amount
ggplot(data.frame(mean_tip_pct_holder),aes(mean_tip_pct_holder))+geom_histogram()+
  labs(title="Sampling Distribution of Average Tip Percents",
       x="Tip Percent of Fare", y="Count")
```
</div>
<div data-sample-ID="sample-by-borough"
     data-tags="sample,data,borough">
```{r sample-by-borough}

boroughs <- unique(taxi$Borough_pickup)

full_results <- data.frame(
  PU_Borough = character(),
  DO_Borough = character(),
  mean_tip = numeric(),
  mean_fare = numeric(),
  mean_tip_pct = numeric(),
  mean_distance = numeric(),
  mean_duration = numeric(),
  stringsAsFactors = FALSE
)
set.seed(123)
for (b in boroughs) {

  pu_data <- taxi %>% filter(Borough_pickup == b)

  for (d in boroughs) {

    pu_do_data <- pu_data %>% filter(Borough_dropoff == d)

    for (i in 1:100) {

      id <- sample(1:nrow(pu_do_data), 100,replace=TRUE)

      tmp <- pu_do_data[id, ] %>%
        filter(tip_amount / fare_amount < 1) %>%
        summarize(
          mean_tip      = mean(tip_amount),
          mean_fare     = mean(fare_amount),
          mean_tip_pct  = mean(tip_amount / fare_amount),
          mean_dist     = mean(trip_distance),
          mean_duration = mean(duration)
        )

      full_results <- rbind(
        full_results,
        data.frame(
          PU_Borough = b,
          DO_Borough = d,
          mean_tip = tmp$mean_tip,
          mean_fare = tmp$mean_fare,
          mean_tip_pct = tmp$mean_tip_pct,
          mean_distance = tmp$mean_dist,
          mean_duration = tmp$mean_duration
        )
      )
    }
  }
}

```
</div>

<div data-plot-id="mean_tip_by_pickup_borough"
     data-tags="tips,tip,amount,borough,sampling,pickup,distribution,taxi">
```{r}
# On average, we see higher tips for pickup locations in EWR and Queens while we see lower tips for pickup locations in Bronx, Brooklyn, and Staten Island
full_results %>% ggplot(aes(mean_tip,fill=PU_Borough)) + geom_histogram(col="black")+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Tips by Pickup Borough", x="Mean Tip Amounts", y="Count")
```
</div>

<div data-plot-id="mean_tip_by_pickup_and_dropoff_borough"
     data-tags="tips,tip,amount,borough,sampling,distribution,taxi,pickup,dropoff">
```{r}
# Trips between EWR and Queens or between Queens and EWR have the highest average tips
# Trips with Pickup or dropoff in Bronx typically have lower average tips
# trips with pickup and drop off in Manhattan have low tips
plot_data = full_results %>%
  group_by(PU_Borough,DO_Borough) %>%
  summarize(mean_tip = mean(mean_tip), .groups="drop")

plot_data %>% ggplot(aes(DO_Borough, mean_tip,fill=DO_Borough)) + geom_col()+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Tips by Pickup Borough", x="Mean Tip Amounts", y="Count")
```
</div> 

<div data-plot-id="mean_fare_by_pickup_borough"
     data-tags="fare,amount,borough,sampling,pickup,distribution,taxi">
```{r}
# We see the highest average fares for pickup locations in EWR while we see our lowest average fares for pickup locations in Bronx, Brooklyn, and Staten Island with medium average fares for pickup locations in Queens
full_results %>% ggplot(aes(mean_fare,fill=PU_Borough)) + geom_histogram(col="black")+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Fares by Pickup Borough", x="Mean Fare Amounts", y="Count")
```
</div>

<div data-plot-id="mean_tip_pct_by_pickup_borough"
     data-tags="tip,tips,percent,borough,sampling,pickup,distribution,taxi">
```{r}
# We see the highest average tip percent for pickup locations in Manhattan while we see the lowest average tip percents for pickup locations in Bronx, Brooklyn, and Staten Island with mid-range average tip percents for pickup locations in EWR and Queens
full_results %>% ggplot(aes(mean_tip_pct,fill=PU_Borough)) + geom_histogram(col="black")+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Tip Percent of Fare by Pickup Borough", x="Mean Tip Percent Amounts", y="Count")
```
</div>

<div data-plot-id="Insights_tips_fare_percent_by_pickup_borough"
     data-table-tags="insights,tips,fares,percent,borough,distances">
```{r insights}
insights <- data.frame(Pickup_Borough = c("Bronx","Brooklyn","EWR","Manhattan","N/A","Queens","Staten Island","Unknown"),
                       Tips = c("Low","Low","High","Low","High","High","Low","Medium"),
                       Fares = c("Low","Low","High","Low","High","Medium","Low","Low"),
                       Percent = c("Low","Low","Medium","High","Medium","Medium","Low","High"))
# For Pickup locations in Bronx, Brooklyn, and Staten Island, fares and percentage is low, so tip amounts are also low
# For pickup locations in EWR, N/A, and Queens, average fares are medium/higher, but percentage is medium, resulting in high tip amounts
# For pickup locations in Manhattan and Unknown, fares are low, so even with a high percentage, average tips will still be low
# No pickup boroughs had high average fares and low average tips
insights
```
</div>
<div data-plot-id="mean_distance_by_pickup_borough"
     data-tags="distance,borough,sampling,pickup,distribution,taxi">
```{r}
# Trips with pickup in the Bronx have various average distances from 0 to 40 miles
# Trips with pickup in EWR and Queens have normally distributed average distances with averages around 15 miles
# Trips with pickup in Manhattan all average under 25 miles
# Trips with pickup in Staten Island have various average distances from 0 to 30 Miles
full_results %>% ggplot(aes(mean_distance,fill=PU_Borough)) + geom_histogram(col="black")+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Trip Distances by Borough", x="Mean Trip Distance", y="Count")+
  xlim(0,40)
```
</div>

<div data-plot-id="mean_duration_by_pickup_borough"
     data-tags="duration,borough,sampling,pickup,distribution,taxi">
```{r}
# Trips with pickup in the Bronx, EWR, Queens have various average trip duration from 0 to 80 minutes
# Trips with pickup in Brooklyn, Staten Island, and Manhattan have narrower average duration between 10 and 50 minutes
full_results %>% ggplot(aes(mean_duration,fill=PU_Borough)) + geom_histogram(col="black")+ facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Trip Distances by Borough", x="Mean Trip Distance", y="Count")
```
</div>

<div data-plot-id="mean_duration_vs_tip_by_pickup_borough"
     data-tags="duration,borough,sampling,pickup,scatter,taxi">
```{r}
# Tip values are tightly clustered for each pickup and drop off pair
full_results %>% ggplot(aes(mean_duration,mean_tip)) + geom_point(aes(col=DO_Borough)) + geom_smooth(method="lm") +
  facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Trip Duration by Pickup Borough", x="Mean Trip Duration", y="Mean Tip Amounts",
       color = "Drop Off Borough")
```
</div>

<div data-plot-id="mean_distance_vs_tip_by_pickup_borough"
     data-tags="distance,borough,sampling,pickup,scatter,taxi">
```{r}
# Longer trip distances have an association with higher tips, with the exception of a few unusual cases with a pickup in EWR and dropoff in the Bronx had unusually long trip distances
full_results %>% ggplot(aes(mean_distance,mean_tip)) + geom_point(aes(col=DO_Borough)) + geom_smooth(method="lm") +
  facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Trip Distances by Pickup Borough", x="Mean Trip Distance", y="Mean Tip Amounts",
       color = "Drop Off Borough")
```
</div>

<div data-plot-id="mean_fare_vs_tip_by_pickup_borough"
     data-tags="fare,borough,sampling,pickup,scatter,taxi">
```{r}
# Average fares have a strong association with higher tip amounts, regardless of pickup and drop off combinations
full_results %>% ggplot(aes(mean_fare,mean_tip)) + geom_point(aes(col=DO_Borough)) + geom_smooth(method="lm") +
  facet_wrap(~PU_Borough)+
  labs(title = "Sampling Distribution of Mean Fares by Pickup Borough", x="Mean Fare", y="Mean Tip Amounts",
       color = "Drop Off Borough")
```
</div>

<div data-plot-id="tip_amount_vs_rate_code"
     data-tags="fare,borough,sampling,pickup,scatter,taxi">
```{r}
# Standard rate code has the lowest average tip amount while Nassau/Westchester, Negotiated, and Newark rate codes have the highest average tip amounts
taxi_sample %>% ggplot(aes(Ratecode_name,tip_amount,fill = Ratecode_name)) + geom_boxplot() + 
  labs(title = "Tip Amount vs. Rate Code", x="Rate Code", y="Tip Amount", fill= "Rate Code")
```
</div>